[build-system]
requires = ["dataclassy", "methodtools", "numpy", "setuptools >= 42", "setuptools_scm[toml]>=3.4", "slurm_python_utils", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
