::--------------------------------------------------------------------
:: Will take a log file generated by MATLAB, and only echo
:: back those lines that start with a #, to filter out other output
:: Alex Szalay, Baltimore, 2018-07-15
::
:: Usage: matlabEcho logfile
::--------------------------------------------------------------------
@ECHO OFF
::
SETLOCAL enabledelayedexpansion
::
FOR /f "tokens=* delims=" %%G in ('findstr # %1') do (
SET new=%%G
ECHO !new:~1!
)
::
ENDLOCAL 